(function () {
  const ageGroup = localStorage.getItem('zenora_age_group') || '25-35';
  const data = {}; let step = 0;
  const common = [
    { kicker: 'A gentle baseline', title: 'How are you feeling lately?', description: 'There are no right answers. A clear starting point helps you choose a kinder next step.', questions: [{ key: 'sleep_quality', label: 'Sleep quality', hint: '1 = very disrupted · 10 = deeply restorative', type: 'scale' }, { key: 'stress_level', label: 'Current stress', hint: '1 = very low · 10 = overwhelming', type: 'scale' }, { key: 'energy_levels', label: 'Daytime energy', hint: '1 = depleted · 10 = consistently energised', type: 'scale' }] },
    { kicker: 'Patterns, not judgement', title: 'What would you like to shift?', description: 'Select any areas that feel relevant right now. You can always change or skip these later.', questions: [{ key: 'priority_habits', label: 'Your current focus areas', hint: 'Choose any that apply.', type: 'choices', multiple: true, options: ['Stress & overwhelm', 'Sleep routine', 'Screen time', 'Procrastination', 'Caffeine', 'Nicotine or smoking', 'Alcohol', 'Eating patterns', 'Work-life balance'] }] },
    { kicker: 'Your support system', title: 'What helps you reset?', description: `Your ${ageGroup} path will begin with small, realistic actions that fit your life.`, questions: [{ key: 'support_style', label: 'Preferred support', hint: 'Pick the style you are most likely to use.', type: 'choices', options: ['Quiet reflection', 'Structured routine', 'Short guided practices', 'Data & progress', 'Gentle accountability'] }, { key: 'change_readiness', label: 'Readiness for one small change', hint: '1 = just exploring · 10 = ready to begin', type: 'scale' }] },
    { kicker: 'Strengths first', title: 'What is already working?', description: 'This gives your first Zenora dashboard something positive to build on.', questions: [{ key: 'positive_habits', label: 'Existing wellbeing practices', hint: 'Choose any that are part of your life today.', type: 'choices', multiple: true, options: ['Movement', 'Meditation or breathing', 'Time in nature', 'Hydration', 'Journaling', 'Connection', 'Learning', 'Healthy meals'] }, { key: 'personal_intention', label: 'A private intention (optional)', hint: 'A few words are enough.', type: 'text', placeholder: 'For example: leave work with more energy for my family.' }] }
  ];
  const elements = { kicker: document.getElementById('section-kicker'), title: document.getElementById('section-title'), description: document.getElementById('section-description'), questions: document.getElementById('questions'), back: document.getElementById('back'), next: document.getElementById('next'), form: document.getElementById('assessment-form'), error: document.getElementById('assessment-error'), fill: document.getElementById('progress-fill'), progress: document.getElementById('progress-text'), step: document.getElementById('assessment-step') };
  const escape = (value) => String(value).replace(/[&<>"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[char]);
  const render = () => { const section = common[step]; elements.kicker.textContent = section.kicker; elements.title.textContent = section.title; elements.description.textContent = section.description; elements.step.textContent = `Check-in ${step + 1} of ${common.length}`; const pct = ((step + 1) / common.length) * 100; elements.fill.style.width = `${pct}%`; elements.progress.textContent = `${Math.round(pct)}% complete`; elements.back.hidden = step === 0; elements.next.textContent = step === common.length - 1 ? 'Finish & open Zenora' : 'Continue'; elements.error.textContent = '';
    elements.questions.innerHTML = section.questions.map((question) => { if (question.type === 'scale') return `<fieldset class="question"><legend>${escape(question.label)}</legend><small>${escape(question.hint)}</small><div class="scale">${Array.from({ length: 10 }, (_, i) => { const value = i + 1; const id = `${question.key}-${value}`; return `<input id="${id}" name="${question.key}" value="${value}" type="radio" ${data[question.key] === value ? 'checked' : ''}><label for="${id}">${value}</label>`; }).join('')}</div></fieldset>`; if (question.type === 'choices') return `<fieldset class="question"><legend>${escape(question.label)}</legend><small>${escape(question.hint)}</small><div class="choice-list">${question.options.map((option, i) => { const id = `${question.key}-${i}`; const active = question.multiple ? (data[question.key] || []).includes(option) : data[question.key] === option; return `<input id="${id}" name="${question.key}" value="${escape(option)}" type="${question.multiple ? 'checkbox' : 'radio'}" ${active ? 'checked' : ''}><label for="${id}">${escape(option)}</label>`; }).join('')}</div></fieldset>`; return `<div class="question"><label for="${question.key}">${escape(question.label)}</label><small>${escape(question.hint)}</small><input class="zen-input" id="${question.key}" name="${question.key}" value="${escape(data[question.key] || '')}" placeholder="${escape(question.placeholder)}"></div>`; }).join(''); };
  const persistStep = () => { for (const question of common[step].questions) { if (question.type === 'scale' || (question.type === 'choices' && !question.multiple)) { const selected = elements.form.querySelector(`[name="${question.key}"]:checked`); if (selected) data[question.key] = question.type === 'scale' ? Number(selected.value) : selected.value; } else if (question.type === 'choices') data[question.key] = [...elements.form.querySelectorAll(`[name="${question.key}"]:checked`)].map((input) => input.value); else data[question.key] = elements.form.elements[question.key].value.trim(); } };
  elements.form.addEventListener('submit', async (event) => { event.preventDefault(); persistStep(); if (step < common.length - 1) { step += 1; render(); return; } elements.next.disabled = true; elements.next.textContent = 'Saving securely…'; const session = await checkAuthSession(); if (!session) return; try { const payload = { age_group: ageGroup, completed_at: new Date().toISOString(), ...data }; const { error } = await window.supabaseClient.from('wellness_survey').insert({ user_id: session.user.id, scores: payload, created_at: new Date().toISOString() }); if (error) throw error; localStorage.setItem('zenora_assessment_complete', 'true'); window.location.assign('dashboard.html'); } catch (error) { elements.error.textContent = error.message || 'Your check-in could not be saved. Please try again.'; elements.next.disabled = false; elements.next.textContent = 'Finish & open Zenora'; } });
  elements.back.addEventListener('click', () => { persistStep(); step -= 1; render(); }); render();
})();
