// ==========================================
// ZENORA AI - MAIN APPLICATION SCRIPT
// ==========================================

/**
 * Checks if the user is currently authenticated with Supabase.
 * @param {boolean} redirectOnFail - If true, redirects unauthenticated users to index.html.
 * @returns {Promise<Object|null>} Supabase session or null.
 */
async function checkAuthSession(redirectOnFail = true) {
  if (!window.supabaseClient) {
    console.warn("Supabase client is not initialized.");
    return null;
  }

  try {
    const { data: { session }, error } = await window.supabaseClient.auth.getSession();

    if (error || !session) {
      console.warn("No active session found or auth check failed.");
      if (redirectOnFail) {
        window.location.href = 'index.html';
      }
      return null;
    }

    return session;
  } catch (err) {
    console.error("Auth session check exception:", err);
    if (redirectOnFail) {
      window.location.href = 'index.html';
    }
    return null;
  }
}

/**
 * Sends a user prompt to Vercel's serverless backend (/api/chat).
 * @param {string} promptText - The prompt message to send.
 * @returns {Promise<string>} The response generated by the AI model.
 */
async function callGroqAI(promptText) {
  try {
    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        prompt: promptText
      })
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error || 'Groq AI Request Failed');
    }

    // OpenAI standard completion payload checks
    if (data.choices && data.choices[0]?.message?.content) {
      return data.choices[0].message.content;
    } else if (data.reply) {
      return data.reply;
    } else {
      throw new Error('Invalid response structure received from server.');
    }
  } catch (error) {
    console.error('callGroqAI Error:', error);
    throw error;
  }
}

/**
 * Handles user logout across Supabase auth and local browser storage.
 */
function handleLogout() {
  const clearLocalStorage = () => {
    localStorage.removeItem('zenora_user');
    localStorage.removeItem('zenora_user_session');
    window.location.href = 'index.html';
  };

  if (window.supabaseClient) {
    window.supabaseClient.auth.signOut()
      .then(clearLocalStorage)
      .catch((err) => {
        console.error("Sign-out error:", err);
        clearLocalStorage();
      });
  } else {
    clearLocalStorage();
  }
}

/**
 * DOM Event Listeners & Chat UI Handler
 */
document.documentElement.dataset.theme = (() => {
  try { return JSON.parse(localStorage.getItem('zenora_preferences') || '{}').theme || 'cosmic'; } catch (_) { return 'cosmic'; }
})();

document.addEventListener('DOMContentLoaded', async () => {
  // Optional auth verification check on dashboard load
  if (window.location.pathname.includes('dashboard.html')) {
    await checkAuthSession(true);
  }

  const chatForm = document.getElementById('chat-form');
  const chatInput = document.getElementById('chat-input');
  const chatMessages = document.getElementById('chat-messages');

  if (chatForm && chatInput && chatMessages) {
    chatForm.addEventListener('submit', async (e) => {
      e.preventDefault();

      const userText = chatInput.value.trim();
      if (!userText) return;

      // 1. Display User Message
      appendMessage(userText, 'user');
      chatInput.value = '';

      // 2. Display Temporary Loading Message
      const loadingMessage = appendMessage('Zenora AI is thinking...', 'ai-loading');

      try {
        // 3. Request AI Completion
        const aiReply = await callGroqAI(userText);

        // Remove loading state & add actual AI response
        if (loadingMessage) loadingMessage.remove();
        appendMessage(aiReply, 'ai');

      } catch (err) {
        if (loadingMessage) loadingMessage.remove();
        appendMessage('Error: ' + (err.message || 'Failed to get a response.'), 'error');
      }
    });
  }
});

/**
 * Helper to render chat message bubbles.
 * @param {string} text - Message text to display.
 * @param {string} sender - Message type ('user', 'ai', 'ai-loading', 'error').
 * @returns {HTMLElement|null} The created message node.
 */
function appendMessage(text, sender) {
  const chatMessages = document.getElementById('chat-messages');
  if (!chatMessages) return null;

  const msgDiv = document.createElement('div');
  msgDiv.classList.add('message', sender);
  msgDiv.textContent = text;

  chatMessages.appendChild(msgDiv);
  chatMessages.scrollTop = chatMessages.scrollHeight; // Keep view scrolled to latest message

  return msgDiv;
}
